# Generated by Django 3.0.4 on 2020-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strongTitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('btnTitle', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/hero/')),
            ],
        ),
    ]
