# Generated by Django 3.0.4 on 2020-10-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keranjang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keranjang',
            name='rating',
        ),
    ]
