# Generated by Django 3.0.4 on 2020-10-04 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
        ('keranjang', '0002_remove_keranjang_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keranjang',
            name='gambar',
        ),
        migrations.RemoveField(
            model_name='keranjang',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='keranjang',
            name='nama',
        ),
        migrations.AddField(
            model_name='keranjang',
            name='makanan',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='makanan.Makanan'),
            preserve_default=False,
        ),
    ]
