# Generated by Django 3.0.4 on 2020-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.FloatField()),
                ('rating', models.FloatField()),
                ('gambar', models.ImageField(upload_to='makanan/')),
            ],
        ),
    ]
